services:
  wled-mqtt-bridge:
    image: ghcr.io/tobiaswaelde/wled-mqtt-bridge:${IMAGE_TAG:-latest}
    restart: unless-stopped
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./config:/app/config
    ports:
      - "3000:3000"
