mqtt:
  host: mqtt.example.net
  clientId: '' # Leave empty to generate a UUID at startup.
  username: mqtt-user
  password: change-me
instances:
  - id: desk
    topic: home/wled/desk
    host: 192.168.1.30
    pingInterval: 15000
    pongTimeout: 5000
    reconnectInterval: 15000
  - id: kitchen
    topic: home/wled/kitchen
    host: 192.168.1.31
